// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhsdwyufzigoyzzeengl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhoc2R3eXVmemlnb3l6emVlbmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjA3MDgsImV4cCI6MjA2MTczNjcwOH0.cmxcK_LHyP680B7Pi3hZ9ItufGvQHFengkxci1sR3LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);